# Generated by Django 4.2.1 on 2023-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('dairy_free', models.BooleanField(default=False)),
                ('extended_ingredients', models.JSONField(default=list)),
                ('recipe_id', models.IntegerField(unique=True)),
                ('ready_in_minutes', models.IntegerField()),
                ('image', models.URLField(max_length=255)),
                ('dish_types', models.JSONField(default=list)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
