# Generated by Django 4.2.1 on 2023-05-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicmenuapi', '0002_mmuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmuser',
            old_name='dairyFree',
            new_name='dairy_free',
        ),
        migrations.RenameField(
            model_name='mmuser',
            old_name='glutenFree',
            new_name='gluten_free',
        ),
    ]
