# Generated by Django 4.2.1 on 2023-05-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicmenuapi', '0003_rename_dairyfree_mmuser_dairy_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('friday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_menus', to='magicmenuapi.recipe')),
                ('monday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_menus', to='magicmenuapi.recipe')),
                ('saturday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_menus', to='magicmenuapi.recipe')),
                ('sunday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_menus', to='magicmenuapi.recipe')),
                ('thursday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_menus', to='magicmenuapi.recipe')),
                ('tuesday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_menus', to='magicmenuapi.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='magicmenuapi.mmuser')),
                ('wednesday_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_menus', to='magicmenuapi.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicmenuapi.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='magicmenuapi.mmuser')),
            ],
        ),
    ]
